spring:
  profiles:
    active: dev
  rabbitmq:
        host: my-docker-ip
        port: 5672
        username: guest
        password: guest
  data:
       mongodb:
           uri: mongodb://localhost:27017    
           database: userMongo
       solr:
         host: http://localhost:8983/solr
         #zk-host:  => to initialize if ever we use zookeeper in dev environment
         core: flash
  datasource:   
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/user
    name: userDB
    username: root
    password: root
    xa:
      data-source-class-name: org.mariadb.jdbc.MySQLDataSource
    test-while-idle: true
    validationQuery: SELECT 1
  batch:
    job:
      enabled: false
      initializer:
         enabled: false
batch:
  pageSize: 1
  threadPoolSize: 4
  throttleLimit: 4

ecm-core:
    xsltTransformation:
      xslLogPath: file:/tmp/log/
    xmlImport:
      dateFormat: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
      defaultCreatorLogin: slequime
    #Config for Async / RabbitMQ
    async:
      appId: 'ecm-core' #Sender App identifiant
      solrQueue: 'solr-dev.queue' #Name of Solr Queue
      basexQueue: 'basex-dev.queue' #Name of Basex Queue
      enabled: false


